on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set short SHA
      id: short_sha
      run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        MSG_MINIMAL: actions url, event
        SLACK_TITLE: 'Dev環境へのデプロイ結果'
        SLACK_MESSAGE: "${{ job.status == 'success' && '成功しました:rocket:' || '失敗しました:x:' }} (${{ github.event.pull_request.html_url != '' && format('PR: <{0}|#{1}>', github.event.pull_request.html_url, github.event.pull_request.number) || format('コミット: <{0}/{1}/commit/{2}|{3}>', github.server_url, github.repository, github.sha, env.SHORT_SHA) }})"
        SLACK_FOOTER: '${{ github.event.pull_request.html_url || github.event.head_commit.url }}'
