on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch: # 手動実行のトリガーを追加

jobs:
  deploy-dev:
    name: Deploy to Development
    if: |
      github.ref == 'refs/heads/main' && 
      (!contains(github.event.head_commit.message, '[skip deploy]') || contains(github.event.head_commit.message, '[force deploy]'))
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          MSG_MINIMAL: commit,actions url
          SLACK_MESSAGE: "Dev環境へのデプロイが${{ job.status == 'success' && '成功しました:mp_100:' || '失敗しました:x:' }}"
          SLACK_FOOTER: ${{ github.event_name == 'workflow_dispatch' && '手動実行によるデプロイ' || github.event.head_commit.message }}
