on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        MSG_MINIMAL: commit,actions url
        SLACK_MESSAGE: "Dev環境へのデプロイが${{ job.status == 'success' && '成功しました:mp_100:' || '失敗しました:x:' }}"
        SLACK_FOOTER: ${{ github.event_name == 'workflow_dispatch' && '手動実行によるデプロイ' || github.event.head_commit.message }}