on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: 'Deploy Notification'
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/github.png?size=48
        SLACK_TITLE: 'Dev環境へのデプロイ結果'
        SLACK_MESSAGE: '${{ job.status == 'success' && "成功" || "失敗" }}しました。'
        SLACK_FOOTER: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
